### ISSUE TITLE
 java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by john-alstru** [ria-ee/X-Road#15]
Hello,

I got a Java OutOfMemoryError  when running ./build_packages.sh script. 
I set the org.gradle.jvmargs=-Xms128m -Xmx512m in the gradle.properties.
But it still got the same error. 
Is the gradle.properties right place to set jvm options?
What's the recommended jvm memory size?

Thanks.

```
Mar 16, 2017 11:29:28 AM com.sun.xml.internal.messaging.saaj.soap.EnvelopeFactory createEnvelope
SEVERE: SAAJ0511: Unable to create envelope from given source
Exception in thread "main" 
                           java.lang.OutOfMemoryError: Java heap space
        at java.lang.StringCoding.encode(StringCoding.java:350)
        at java.lang.String.getBytes(String.java:941)
        at ee.ria.xroad.proxy.testsuite.MessageTestCase.changeQueryId(MessageTestCase.java:446)
        at ee.ria.xroad.proxy.testsuite.MessageTestCase.getQueryInputStream(MessageTestCase.java:343)
        at ee.ria.xroad.proxy.testsuite.MessageTestCase.getRequestInput(MessageTestCase.java:334)
        at ee.ria.xroad.proxy.testsuite.MessageTestCase.execute(MessageTestCase.java:247)
        at ee.ria.xroad.proxy.testsuite.ProxyTestSuite.runTestCases(ProxyTestSuite.java:238)
        at ee.ria.xroad.proxy.testsuite.ProxyTestSuite.runTestSuite(ProxyTestSuite.java:223)
        at ee.ria.xroad.proxy.testsuite.ProxyTestSuite.runNormalTestCases(ProxyTestSuite.java:171)
        at ee.ria.xroad.proxy.testsuite.ProxyTestSuite.main(ProxyTestSuite.java:111)
```

**Comment by iluwatar** [comment]
It seems to run out of memory during proxy tests. I haven't measured the memory the build and all the included tests need. Can you increase the memory your build machine has? The other option is to run the build excluding the tests.

**Comment by jhyoty** [comment]
The proxy test suite is run as a separate process and the gradle properties have no effect. Running the test suite requires about 1GiB of heap, but the build uses the default jvm memory settings (max heap size is about 1/4 of of total memory).
You can fix this manually by editing the runProxyTest task src/proxy/build.gradle: Add parameter `maxHeapSize = '1g' ` .

**Comment by john-alstru** [comment]
@jhyoty OutOfMemoryError exception is solved by setting `maxHeapSize = '1g'`, but I still got other errors. I'll try it later on.

@iluwatar I remove `runProxyTest` task from compile_code.sh, so it all worked well.

I still have some problems when building packages and I'll start a new issue.

Thank you all.
