### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by zhtlee** [ria-ee/X-Road#40]
hello,@iluwatar @tuudik 
[INFO] [05/03/2017 22:04:31.352] [Proxy-akka.remote.default-remote-dispatcher-5] [akka.tcp://Proxy@127.0.0.1:37885/system/remoting-terminator] Shutting down remote daemon.
[INFO] [05/03/2017 22:04:31.380] [Proxy-akka.remote.default-remote-dispatcher-5] [akka.tcp://Proxy@127.0.0.1:37885/system/remoting-terminator] Remote daemon shut down; proceeding with flushing remote transports.
[INFO] [05/03/2017 22:04:31.551] [Proxy-akka.actor.default-dispatcher-3] [akka.remote.Remoting] Remoting shut down
[INFO] [05/03/2017 22:04:31.556] [Proxy-akka.remote.default-remote-dispatcher-5] [akka.tcp://Proxy@127.0.0.1:37885/system/remoting-terminator] Remoting shut down.
22:23:31.472 [Timer-0] ERROR e.r.x.proxy.testsuite.ProxyTestSuite - Test suite is taking too long, exiting
:proxy:runProxyTest FAILED

FAILURE: Build failed with an exception.
How to solve this problem? thanks!

**Comment by iluwatar** [comment]
@zhtlee can you please post the whole build log? Can you reproduce it every time? What is the software version?

**Comment by zhtlee** [comment]
@iluwatar the software version is Estonian 6.14.0，I do serveral times ,I got same log ervery times.
[build_2017-05-05_15-35-25.txt](https://github.com/ria-ee/X-Road/files/978455/build_2017-05-05_15-35-25.txt)

**Comment by zhtlee** [comment]
if build successful,where do I find the package?

**Comment by zhtlee** [comment]
mistake to close just now

**Comment by iluwatar** [comment]
It seems to run out of memory `Exception in thread "main" java.lang.OutOfMemoryError: Java heap space`. Please try the solution described in https://github.com/ria-ee/X-Road/issues/15.

**Comment by zhtlee** [comment]
@iluwatar  Thanks for you answer.I remove runProxyTest task from compile_code.sh, so it all worked well.but I did not find the builded Package . where do I find the package?

**Comment by iluwatar** [comment]
compile_code.sh does not build the packages but there is another script for that called build_packages.sh.

**Comment by zhtlee** [comment]
@iluwatar I remove runProxyTest task from compile_code.sh, but I run  build_packages.sh. I do not find  the package. build_2017-05-05_15-35-25.txt is the log when I run build_packages.sh

**Comment by iluwatar** [comment]
The build log you mentioned (build_2017-05-05_15-35-25.txt) fails with error `Exception in thread "main" java.lang.OutOfMemoryError: Java heap space`. That's why it does not try to run the packaging. Please study scripts https://github.com/ria-ee/X-Road/blob/develop/src/build_packages.sh and https://github.com/ria-ee/X-Road/blob/develop/src/compile_code.sh.

**Comment by zhtlee** [comment]
@iluwatar  Sorry , I do not say clear. I remove runProxyTest task from compile_code.sh, and then I run build_packages.sh, and  I get success. but I do not know where I can find the package.

**Comment by iluwatar** [comment]
After build success you can do `find -name *.deb` and `find -name *.rpm` to find them. They should be located under `src/packages`.

**Comment by zhtlee** [comment]
@iluwatar  OutOfMemoryError exception is solved by setting  maxHeapSize = '1g' , but I still got other errors. 

:monitor-test:processResources UP-TO-DATE
:monitor-test:classes
:monitor-test:jar UP-TO-DATE
:monitor-test:startScripts
:monitor-test:distTar
:monitor-test:distZip
:monitor-test:sourcesJar UP-TO-DATE
:monitor-test:assemble
:monitor-test:checkstyleMain UP-TO-DATE
:monitor-test:compileTestJava UP-TO-DATE
:monitor-test:processTestResources UP-TO-DATE
:monitor-test:testClasses UP-TO-DATE
:monitor-test:checkstyleTest UP-TO-DATE
:monitor-test:licenseMain UP-TO-DATE
:monitor-test:licenseTest UP-TO-DATE
:monitor-test:license UP-TO-DATE
:monitor-test:test UP-TO-DATE
:monitor-test:check UP-TO-DATE
:monitor-test:build
:monitor-test:buildall
:monitoring-conf:processResources UP-TO-DATE
:monitoring-conf:createDirs UP-TO-DATE
:monitoring-conf:xjc
---- monitoring xjc @ execution phase
:monitoring-conf:compileJava
:monitoring-conf:classes
:monitoring-conf:jar UP-TO-DATE
:monitoring-conf:sourcesJar
:monitoring-conf:assemble
:monitoring-conf:checkstyleMain
:monitoring-conf:compileTestJava
:monitoring-conf:processTestResources UP-TO-DATE
:monitoring-conf:testClasses
:monitoring-conf:checkstyleTest UP-TO-DATE
:monitoring-conf:licenseMain SKIPPED
:monitoring-conf:licenseTestJava UP-TO-DATE
:monitoring-conf:licenseTest UP-TO-DATE
:monitoring-conf:license UP-TO-DATE
:monitoring-conf:test
:monitoring-conf:check
:monitoring-conf:build
:monitoring-conf:buildall
:op-monitor-daemon:processResources UP-TO-DATE
:op-monitor-daemon:createDirs UP-TO-DATE
:op-monitor-daemon:xjc
---- op-monitor-daemon xjc @ configuration phase
---- op-monitor-daemon xjc @ execution phase
[ant:xjc] [ERROR] External DTD: Failed to read external DTD 'xhtml1-transitional.dtd', because 'http' access is not allowed due to restriction set by the accessExternalDTD property.
[ant:xjc]   line 1 of http://10.3.254.233/webAuth/index.htm?ws-i.org/profiles/basic/1.1/swaref.xsd
[ant:xjc] 
:op-monitor-daemon:xjc FAILED

FAILURE: Build failed with an exception.

* Where:
Build file '/home/putian11/X-Road-develop/src/op-monitor-daemon/build.gradle' line: 54

* What went wrong:
Execution failed for task ':op-monitor-daemon:xjc'.
> unable to parse the schema. Error messages should have been provided

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':op-monitor-daemon:xjc'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:66)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:25)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:110)
        at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
        at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
        at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
        at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
        at org.gradle.initialization.DefaultGradleLauncher$4.run(DefaultGradleLauncher.java:153)
        at org.gradle.internal.Factories$1.create(Factories.java:22)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:53)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:150)
        at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:98)
        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:92)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:63)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:92)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:83)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:99)
        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:48)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:30)
        at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:81)
        at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:46)
        at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:51)
        at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:28)
        at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:43)
        at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:173)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:239)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:212)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:205)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
        at org.gradle.launcher.Main.doAction(Main.java:33)
        at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:55)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:36)
        at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
        at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:127)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Caused by: : unable to parse the schema. Error messages should have been provided
        at com.sun.tools.xjc.XJC2Task._doXJC(XJC2Task.java:520)
        at com.sun.tools.xjc.XJC2Task.doXJC(XJC2Task.java:457)
        at com.sun.tools.xjc.XJC2Task.execute(XJC2Task.java:380)
        at com.sun.istack.tools.ProtectedTask.execute(ProtectedTask.java:103)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.gradle.api.internal.project.ant.BasicAntBuilder.nodeCompleted(BasicAntBuilder.java:78)
        at org.gradle.api.internal.project.ant.BasicAntBuilder.doInvokeMethod(BasicAntBuilder.java:103)
        at build_ecrg8vav5hyqiugmk3lk5mcwa$_run_closure5$_closure16.doCall(/home/putian11/X-Road-develop/src/op-monitor-daemon/build.gradle:54)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:590)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:571)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
        ... 60 more


BUILD FAILED

Total time: 19 mins 45.493 secs
putian11@ubuntu:~/X-Road-develop/src$

**Comment by zhtlee** [comment]
@iluwatar build success   , but the build_package.sh is not end , can not input any command,and  I did not find the packges.
        PASSED - NotAllowed
        PASSED - CommentMessage
        PASSED - ServiceHttpError
        PASSED - AttachmentFaultySoap
        PASSED - WrongHttpMethod

[INFO] [05/09/2017 04:19:04.898] [Proxy-akka.remote.default-remote-dispatcher-8] [akka.tcp://Proxy@127.0.0.1:40503/system/remoting-terminator] Shutting down remote daemon.
[INFO] [05/09/2017 04:19:05.055] [Proxy-akka.remote.default-remote-dispatcher-8] [akka.tcp://Proxy@127.0.0.1:40503/system/remoting-terminator] Remote daemon shut down; proceeding with flushing remote transports.
[INFO] [05/09/2017 04:19:05.666] [Proxy-akka.actor.default-dispatcher-19] [akka.remote.Remoting] Remoting shut down
[INFO] [05/09/2017 04:19:05.674] [Proxy-akka.remote.default-remote-dispatcher-8] [akka.tcp://Proxy@127.0.0.1:40503/system/remoting-terminator] Remoting shut down.

BUILD SUCCESSFUL

Total time: 34 mins 6.848 secs

This build could be faster, please consider using the Gradle Daemon: https://docs.gradle.org/2.14.1/userguide/gradle_daemon.html
sha256:e1601f69c087756fa973eca266d866857f2ea57c0d2ef825b7ed18977dff1468

**Comment by zhtlee** [comment]
@iluwatar  Thanks ，I build success，and found the the package in src/packages. Before not find the package.
