### ISSUE TITLE
Looking for contacts && Dev environment deps glitching

### ISSUE THREAD

**Issue by Potrimpo** [ria-ee/X-Road#44]
#### Issue details below

Readme instructions (src/Vagrant.md) for setting up development environment point to [old repo.](https://github.com/vrk-kpa/xroad-public)
*I am pulling from the active repo instead* and assuming that it is a mistake (although I get errors building from either source).

When running `./build_packages.sh `

Build fails with following trace

```
:center-ui:warble
warble aborted!
LoadError: Please install the postgresql adapter: `gem install activerecord-postgresql-adapter` (pg is not part of the bundle. Add it to your Gemfile.)
/home/ubuntu/.rvm/gems/jruby-1.7.25/gems/bundler-1.15.0/lib/bundler/rubygems_integration.rb:377:in `gem'
/home/ubuntu/.rvm/gems/jruby-1.7.25/gems/activerecord-3.2.22.5/lib/active_record/connection_adapters/postgresql_adapter.rb:7:in `(root)'
/home/ubuntu/.rvm/gems/jruby-1.7.25/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:251:in `require'
/home/ubuntu/.rvm/gems/jruby-1.7.25/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:236:in `load_dependency'
/home/ubuntu/.rvm/gems/jruby-1.7.25/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:251:in `require'
/home/ubuntu/.rvm/gems/jruby-1.7.25/gems/activerecord-3.2.22.5/lib/active_record/connection_adapters/abstract/connection_specification.rb:1:in `(root)'
/home/ubuntu/.rvm/gems/jruby-1.7.25/gems/activerecord-3.2.22.5/lib/active_record/connection_adapters/abstract/connection_specification.rb:50:in `resolve_hash_connection'
/home/ubuntu/.rvm/gems/jruby-1.7.25/gems/activerecord-3.2.22.5/lib/active_record/connection_adapters/abstract/connection_specification.rb:41:in `resolve_string_connection'
/home/ubuntu/.rvm/gems/jruby-1.7.25/gems/activerecord-3.2.22.5/lib/active_record/connection_adapters/abstract/connection_specification.rb:25:in `spec'
/home/ubuntu/.rvm/gems/jruby-1.7.25/gems/activerecord-3.2.22.5/lib/active_record/connection_adapters/abstract/connection_specification.rb:130:in `establish_connection'
/home/ubuntu/.rvm/gems/jruby-1.7.25/gems/activerecord-3.2.22.5/lib/active_record/railtie.rb:88:in `Railtie'
/home/ubuntu/.rvm/gems/jruby-1.7.25/gems/activesupport-3.2.22.5/lib/active_support/lazy_load_hooks.rb:36:in `execute_hook'
/home/ubuntu/.rvm/gems/jruby-1.7.25/gems/activesupport-3.2.22.5/lib/active_support/lazy_load_hooks.rb:26:in `on_load'
/home/ubuntu/.rvm/gems/jruby-1.7.25/gems/activesupport-3.2.22.5/lib/active_support/lazy_load_hooks.rb:25:in `on_load'
/home/ubuntu/.rvm/gems/jruby-1.7.25/gems/activerecord-3.2.22.5/lib/active_record/railtie.rb:80:in `Railtie'
/home/ubuntu/.rvm/gems/jruby-1.7.25/gems/railties-3.2.22.5/lib/rails/initializable.rb:30:in `run'
/home/ubuntu/.rvm/gems/jruby-1.7.25/gems/railties-3.2.22.5/lib/rails/initializable.rb:55:in `run_initializers'
/home/ubuntu/.rvm/gems/jruby-1.7.25/gems/railties-3.2.22.5/lib/rails/initializable.rb:54:in `run_initializers'
/home/ubuntu/.rvm/gems/jruby-1.7.25/gems/railties-3.2.22.5/lib/rails/application.rb:136:in `initialize!'
/home/ubuntu/.rvm/gems/jruby-1.7.25/gems/railties-3.2.22.5/lib/rails/railtie/configurable.rb:30:in `method_missing'
/home/ubuntu/.rvm/gems/jruby-1.7.25/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:251:in `require'
/home/ubuntu/.rvm/gems/jruby-1.7.25/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:236:in `load_dependency'
/home/ubuntu/.rvm/gems/jruby-1.7.25/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:251:in `require'
/home/ubuntu/X-Road/src/center-ui/config/environment.rb:28:in `(root)'
/home/ubuntu/.rvm/gems/jruby-1.7.25/gems/railties-3.2.22.5/lib/rails/application.rb:1:in `(root)'
/home/ubuntu/.rvm/gems/jruby-1.7.25/gems/railties-3.2.22.5/lib/rails/application.rb:103:in `require_environment!'
/home/ubuntu/.rvm/gems/jruby-1.7.25/gems/railties-3.2.22.5/lib/rails/application.rb:305:in `initialize_tasks'
/home/ubuntu/.rvm/gems/jruby-1.7.25/gems/warbler-1.4.9/lib/warbler/traits/rails.rb:29:in `before_configure'
/home/ubuntu/.rvm/gems/jruby-1.7.25/gems/warbler-1.4.9/lib/warbler/traits.rb:29:in `before_configure'
/home/ubuntu/.rvm/gems/jruby-1.7.25/gems/warbler-1.4.9/lib/warbler/traits.rb:29:in `before_configure'
/home/ubuntu/.rvm/gems/jruby-1.7.25/gems/warbler-1.4.9/lib/warbler/config.rb:213:in `initialize'
config/warble.rb:27:in `initialize'
/home/ubuntu/.rvm/gems/jruby-1.7.25/gems/warbler-1.4.9/lib/warbler/task.rb:46:in `initialize'
/home/ubuntu/.rvm/gems/jruby-1.7.25/gems/warbler-1.4.9/lib/warbler/application.rb:27:in `load_rakefile'
/home/ubuntu/.rvm/gems/jruby-1.7.25/bin/warble:23:in `(root)'
Tasks: TOP => environment
(See full trace by running task with --trace)
:center-ui:warble FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':center-ui:warble'.
> Process 'command 'jruby'' finished with non-zero exit value 1
```

Attempting to install the package via `gem install activerecord-postgresql-adapter` gives following error message:
```
Fetching: pg-0.20.0.gem (100%)
ERROR:  Error installing activerecord-postgresql-adapter:
	pg requires Ruby version >= 2.0.0.
```

Because project uses jruby 1.7.25

I have been exploring the build path and trying to figure this out but coming up empty

**Comment by hanhaka** [comment]
Hi,

what kind of contact are you looking for? Technical or administrative contact?
Getting answers for technical questions, creating a Github issue like this one is good and easy way. Unfortunately we cannot provide any online support but we trying to solve and help with Github issues as much as we can.

If looking for the administrative contact I would suggest writing an informal email to: ria@ria.ee
(In a case no reply received in a couple of days, let me know).

Regards,
Hannu

**Comment by Potrimpo** [comment]
Hi Hannu,

Thanks for the email address, I've fired off a message there - hopefully that will cover the administrative contact.

Still looking for technical solution to the errors when building dev environment.

Many thanks,
Lewis

**Comment by jhyoty** [comment]
The recently released bundler version 1.15.0 seems to break the build. As a workaround, you can manually downgrade to bundler 1.14.6.

    rvm use jruby-1.7.25
    gem uninstall bundler -v1.15.0
    gem install bundler -v1.14.6

**Comment by Potrimpo** [comment]
Brilliant obscure solution - love it!

**Comment by iluwatar** [comment]
>> Readme instructions (src/Vagrant.md) for setting up development environment point to old repo.
I am pulling from the active repo instead and assuming that it is a mistake (although I get errors building from either source).

Thanks for pointing this out. We'll fix the links for the next version.
