### ISSUE TITLE
Shared memory error PIN Central Server

### ISSUE THREAD

**Issue by leviduran** [ria-ee/X-Road#46]
Hi , after central server installation I ran into a problem when creating a new signing key (internal configuration). I typed the requiered PIN and when I click Ok I get a RuntimeException:Cannot open shared memory error

Here is the stacktrace from signer.log

`java.lang.RuntimeException: Cannot open shared memory
	at ee.ria.xroad.common.util.PasswordStore.read(Native Method) ~[signer-1.0.jar:na]
	at ee.ria.xroad.common.util.PasswordStore.getPassword(PasswordStore.java:55) ~[signer-1.0.jar:na]
	at ee.ria.xroad.signer.tokenmanager.token.AbstractTokenWorker.isPinStored(AbstractTokenWorker.java:66) ~[signer-1.0.jar:na]
	at ee.ria.xroad.signer.tokenmanager.token.SoftwareTokenWorker.onUpdate(SoftwareTokenWorker.java:90) [signer-1.0.jar:na]
	at ee.ria.xroad.signer.util.AbstractUpdateableActor.onReceive(AbstractUpdateableActor.java:38) [signer-1.0.jar:na]
	at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:165) [signer-1.0.jar:na]
	at akka.actor.Actor$class.aroundReceive(Actor.scala:484) [signer-1.0.jar:na]
	at akka.actor.UntypedActor.aroundReceive(UntypedActor.scala:95) [signer-1.0.jar:na]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526) [signer-1.0.jar:na]
	at akka.actor.ActorCell.invoke(ActorCell.scala:495) [signer-1.0.jar:na]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257) [signer-1.0.jar:na]
	at akka.dispatch.Mailbox.run(Mailbox.scala:224) [signer-1.0.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_111]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]`

Could it be some step I missed during the build /installation process?
Thanks

**Comment by VitaliStupin** [comment]
Hi! Did you build the packages on the same machine as you installed central server? The shared memory is probably locked by the user you built with and "xroad" user cannot access this shared memory segment.

It could be easily fixed by restarting this machine, or alternatively you could check if shared memory and semaphores are locked by your user with `ipcs -s` and `ipcs -m`. If so these semaphores and memory segments could be removed with `ipcrm -s <semid>` and `ipcrm -m <shmid>` commands.

**Comment by leviduran** [comment]
That seemed to work thanks @VitaliStupin. Quick question not directly related to this, in order for "n" security servers to be able to talk to each other and to the central server which ports should be opened?. Thanks again

**Comment by VitaliStupin** [comment]
Used ports are described in the following documents:
https://github.com/ria-ee/X-Road/blob/develop/doc/Manuals/ig-cs_x-road_6_central_server_installation_guide.md#22-reference-data
https://github.com/ria-ee/X-Road/blob/develop/doc/Manuals/ig-ss_x-road_v6_security_server_installation_guide.md#22-reference-data
But as a quick answer:
Central Server should have TCP 4001 and TCP 80 port opened and
Security Server should have TCP 5500 and TCP 5577 port opened for external connections.

**Comment by leviduran** [comment]
Got it @VitaliStupin  and thanks for the doc reference
