### ISSUE TITLE
Jenkins building gets stuck

### ISSUE THREAD

**Issue by tuudik** [ria-ee/X-Road#55]
Hi!

I am using Jenkins running on Ubuntu 14.04 machine. 
The building get stuck all the time here:
```17:06:28 	PASSED - ServiceFaultyMultipart
17:06:28 	PASSED - UnsignedMessageFromServerProxy
17:06:28 	PASSED - SslToServiceNoAuth
17:06:28 	PASSED - Attachment
17:06:28 
17:06:28 Exception in thread "main" java.net.BindException: Address already in use
17:06:28 	at sun.nio.ch.Net.bind0(Native Method)
17:06:28 	at sun.nio.ch.Net.bind(Net.java:433)
17:06:28 	at sun.nio.ch.Net.bind(Net.java:425)
17:06:28 	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
17:06:28 	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
17:06:28 	at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:298)
17:06:28 	at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
17:06:28 	at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:236)
17:06:28 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
17:06:28 	at org.eclipse.jetty.server.Server.doStart(Server.java:431)
17:06:28 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
17:06:28 	at ee.ria.xroad.proxy.clientproxy.ClientProxy.start(ClientProxy.java:297)
17:06:28 	at ee.ria.xroad.proxy.testsuite.ProxyTestSuite.runTestSuite(ProxyTestSuite.java:223)
17:06:28 	at ee.ria.xroad.proxy.testsuite.ProxyTestSuite.runNormalTestCases(ProxyTestSuite.java:181)
17:06:28 	at ee.ria.xroad.proxy.testsuite.ProxyTestSuite.main(ProxyTestSuite.java:95)
17:06:28 [INFO] [08/14/2017 17:06:28.065] [Proxy-akka.remote.default-remote-dispatcher-5] [akka.tcp://Proxy@127.0.0.1:5567/system/remoting-terminator] Shutting down remote daemon.
17:06:28 [INFO] [08/14/2017 17:06:28.067] [Proxy-akka.remote.default-remote-dispatcher-5] [akka.tcp://Proxy@127.0.0.1:5567/system/remoting-terminator] Remote daemon shut down; proceeding with flushing remote transports.
17:06:28 [INFO] [08/14/2017 17:06:28.107] [Proxy-akka.actor.default-dispatcher-15] [akka.remote.Remoting] Remoting shut down
17:06:28 [INFO] [08/14/2017 17:06:28.109] [Proxy-akka.remote.default-remote-dispatcher-6] [akka.tcp://Proxy@127.0.0.1:5567/system/remoting-terminator] Remoting shut down.
```

My build script is as following:
``` 	echo 'Clone repository'
 	git clone https://github.com/ee-ria/X-Road.git -b develop
        cd X-Road/src

	echo 'Update ruby dependencies'
        ./update_ruby_dependencies.sh
	echo 'Build stage'
        git clean -Xf -d
       ./build_packages.sh
```

I have also tried building from the "Jenkinsfile" but the result is same. I have also launched `./prepare_buildhost.sh`before launching the build in Jenkins. What could be the issue?

**Comment by tuudik** [comment]
Figured it out, ProxyTestSuite, is trying to bind client to port 8080 which was already being used by Jenkins (default config). As a workaround I changed Jenkins port to 9090.

I suggest to change ports in test suites above from 10000 to minimize port binding conflict.
