### ISSUE TITLE
Server.ClientProxy.LoggingFailed.TimestamperFailed

### ISSUE THREAD

**Issue by AnttiLuoma** [ria-ee/X-Road#6]
_From @eramirez-sv on February 10, 2017 21:35_

I have configured a TSA service on the central server, using the sample TSA code from this repository. The same service is configured on my Security Server (shows a solid yellow on the diagnostics page)

1.  The server's /var/log/xroad/proxy.log keeps adding this line:
[Proxy-akka.actor.default-dispatcher-57] ERROR e.r.x.p.messagelog.TimestamperWorker - Timestamper failed for message records [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 29, 15, 16, 17, 18, 30, 19, 20]: InternalError: Could not find TSP certificate for timestamp

2. From the Security Server console, I am able to successfully get a signed response using 'openssl ts' from the TSA service.

3. When trying to call allowMethods or listMethods, it works the first time, after that I get this error
<SOAP-ENV:Fault><faultcode>Server.ClientProxy.LoggingFailed.TimestamperFailed</faultcode><faultstring>Cannot time-stamp messages</faultstring><faultactor/><detail><xroad:faultDetail xmlns:xroad="http://x-road.eu/xsd/xroad.xsd">TimestamperFailed: 
	at ee.ria.xroad.proxy.messagelog.LogManager.verifyCanLogMessage(LogManager.java:410)
	at ee.ria.xroad.proxy.messagelog.LogManager.log(LogManager.java:138)
	at ee.ria.xroad.common.messagelog.AbstractLogManager.onReceive(AbstractLogManager.java:57)
	at ee.ria.xroad.proxy.messagelog.LogManager.onReceive(LogManager.java:176)
	at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:165)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:484)
	at akka.actor.UntypedActor.aroundReceive(UntypedActor.scala:95)
.....

Thanks in advance for your help,

_Copied from original issue: vrk-kpa/xroad-public#32_

**Comment by AnttiLuoma** [comment]
_From @iluwatar on February 13, 2017 8:18_

Please verify that
- Timestamping service is configured with correct certificate on the central server (see https://github.com/vrk-kpa/xroad-public/tree/master/utils/testca section `Configuring the central server to use the test-CA`)
- The security servers have the same timestamping service selected
- Port access from security servers to the timestamping service is allowed (there is no firewall blocking the access)

**Comment by AnttiLuoma** [comment]
_From @eramirez-sv on February 14, 2017 23:16_

Thanks for your answer, after many tests I found that I had a typo in the subject name for my SIGN certificate. The OCSP response kept saying the certificate was good but it was causing the logging error.
Regards,
